# Generated by Django 5.0.6 on 2024-06-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
