# Generated by Django 5.0.6 on 2024-06-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.BigIntegerField(blank=True, max_length=200, null=True),
        ),
    ]
