# Generated by Django 5.0.6 on 2024-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
