# Generated by Django 5.0.6 on 2024-06-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_otp_is_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_expired',
        ),
    ]
